        async function loadPRModule() {
            const tables = ['pr_contacts','pr_communications','pr_meetings','pr_tasks','pr_invoices','pr_bank_notifications'];
            const [c,cm,m,t,inv,b] = await Promise.all(tables.map(tbl => supabaseClient.from(tbl).select('*').order('created_at',{ascending:false})));
            prData.contacts = c.data || []; prData.communications = cm.data || []; prData.meetings = m.data || []; prData.tasks = t.data || []; prData.invoices = inv.data || []; prData.bank = b.data || [];
            renderPRContacts(); renderPRComm(); renderPRMeetings(); renderPRTasks(); renderPRInvoices(); renderPRBank();
        }
        function renderPRContacts() { const tbody = document.getElementById('prContactsBody'); const typeLabels = {client:'عميل',partner:'شريك',media:'إعلام',government:'حكومية',other:'أخرى'}; tbody.innerHTML = prData.contacts.length ? prData.contacts.map(c => `<tr><td>${esc(c.name)}</td><td>${esc(c.organization||'-')}</td><td><span class="badge badge-info">${typeLabels[c.type]||c.type}</span></td><td>${esc(c.phone||'-')}</td><td>${esc(c.email||'-')}</td><td><button class="btn btn-sm btn-secondary" onclick="viewPRContact('${c.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="editPRContact('${c.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_contacts','${c.id}','contacts')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="6" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        function renderPRComm() { const tbody = document.getElementById('prCommBody'); const typeL = {email:'بريد',phone:'هاتف',meeting:'اجتماع',letter:'خطاب',other:'أخرى'}; const dirL = {outgoing:'صادر',incoming:'وارد'}; tbody.innerHTML = prData.communications.length ? prData.communications.map(c => `<tr><td>${c.date}</td><td>${esc(c.contact_name)}</td><td><span class="badge badge-info">${typeL[c.type]||c.type}</span></td><td><span class="badge ${c.direction==='outgoing'?'badge-primary':'badge-warning'}">${dirL[c.direction]}</span></td><td>${esc(c.subject)}</td><td><button class="btn btn-sm btn-secondary" onclick="editPRComm('${c.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_communications','${c.id}','communications')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="6" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        function renderPRMeetings() { const tbody = document.getElementById('prMeetingsBody'); tbody.innerHTML = prData.meetings.length ? prData.meetings.map(m => `<tr><td>${m.date}</td><td>${esc(m.title)}</td><td>${esc(m.location||'-')}</td><td>${esc(m.attendees||'-')}</td><td><button class="btn btn-sm btn-secondary" onclick="viewPRMeeting('${m.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="editPRMeeting('${m.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_meetings','${m.id}','meetings')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="5" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        function renderPRTasks() { const tbody = document.getElementById('prTasksBody'); const priL = {low:'<span class="badge badge-info">منخفضة</span>',medium:'<span class="badge badge-warning">متوسطة</span>',high:'<span class="badge badge-danger">عالية</span>'}; const statL = {pending:'<span class="badge badge-warning">انتظار</span>',in_progress:'<span class="badge badge-primary">جاري</span>',done:'<span class="badge badge-success">مكتمل</span>'}; tbody.innerHTML = prData.tasks.length ? prData.tasks.map(t => `<tr><td>${esc(t.title)}</td><td>${priL[t.priority]||t.priority}</td><td>${statL[t.status]||t.status}</td><td>${t.due_date||'-'}</td><td>${esc(t.assigned_to||'-')}</td><td><button class="btn btn-sm btn-secondary" onclick="viewPRTask('${t.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="editPRTask('${t.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_tasks','${t.id}','tasks')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="6" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        function renderPRInvoices() { const tbody = document.getElementById('prInvoicesBody'); const statL = {pending:'badge-warning',paid:'badge-success',overdue:'badge-danger',cancelled:'badge-info'}; const statAr = {pending:'انتظار',paid:'مدفوعة',overdue:'متأخرة',cancelled:'ملغاة'}; tbody.innerHTML = prData.invoices.length ? prData.invoices.map(inv => `<tr><td style="font-family:var(--font-mono)">${esc(inv.number)}</td><td>${esc(inv.client)}</td><td style="font-family:var(--font-mono)">${parseFloat(inv.amount).toLocaleString()} ${inv.currency}</td><td><span class="badge ${statL[inv.status]}">${statAr[inv.status]}</span></td><td>${inv.date}</td><td>${inv.image_path?`<button class="btn btn-sm btn-secondary" onclick="viewPRInvoice('${inv.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="viewPRImage('${inv.image_path}')"><i class="fas fa-image"></i></button>`:'<span style="color:var(--text-muted)">لا يوجد</span>'}</td><td><button class="btn btn-sm btn-secondary" onclick="printPRInvoice('${inv.id}')" title="طباعة"><i class="fas fa-print"></i></button> <button class="btn btn-sm btn-secondary" onclick="editPRInvoice('${inv.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_invoices','${inv.id}','invoices')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="7" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        function renderPRBank() { const tbody = document.getElementById('prBankBody'); const typeAr = {credit:'إيداع',debit:'سحب',transfer:'تحويل',other:'أخرى'}; const typeBadge = {credit:'badge-success',debit:'badge-danger',transfer:'badge-primary',other:'badge-info'}; tbody.innerHTML = prData.bank.length ? prData.bank.map(b => `<tr><td>${b.date}</td><td>${esc(b.bank_name)}</td><td><span class="badge ${typeBadge[b.notification_type]}">${typeAr[b.notification_type]}</span></td><td style="font-family:var(--font-mono)">${b.amount?parseFloat(b.amount).toLocaleString()+' '+b.currency:'-'}</td><td>${esc(b.reference||'-')}</td><td>${b.image_path?`<button class="btn btn-sm btn-secondary" onclick="viewPRImage('${b.image_path}')"><i class="fas fa-image"></i></button>`:'<span style="color:var(--text-muted)">لا يوجد</span>'}</td><td><button class="btn btn-sm btn-secondary" onclick="printPRBank('${b.id}')" title="طباعة"><i class="fas fa-print"></i></button> <button class="btn btn-sm btn-secondary" onclick="editPRBank('${b.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deletePRRecord('pr_bank_notifications','${b.id}','bank')"><i class="fas fa-trash"></i></button></td></tr>`).join('') : `<tr><td colspan="7" style="text-align:center;padding:32px;">${t('noData')}</td></tr>`; }
        async function viewPRImage(path) { const el = document.getElementById('prImageViewContent'); el.innerHTML = '<i class="fas fa-spinner fa-spin" style="font-size:32px;color:var(--text-muted)"></i>'; openModal('prImageViewModal'); const { data } = await supabaseClient.storage.from('pr-images').createSignedUrl(path, 3600); if (data?.signedUrl) { const isImg = /\.(jpg|jpeg|png|webp)$/i.test(path); el.innerHTML = isImg ? `<img src="${data.signedUrl}" style="max-width:100%;max-height:70vh;border-radius:var(--radius-lg);">` : `<a href="${data.signedUrl}" target="_blank" class="btn btn-primary"><i class="fas fa-file-pdf"></i> فتح الملف</a>`; } else { el.innerHTML = '<p style="color:var(--danger)">تعذّر تحميل الصورة</p>'; } }
        async function savePRContact() { const payload = { name: document.getElementById('prContactName').value.trim(), organization: document.getElementById('prContactOrg').value.trim()||null, type: document.getElementById('prContactType').value, phone: document.getElementById('prContactPhone').value.trim()||null, email: document.getElementById('prContactEmail').value.trim()||null, address: document.getElementById('prContactAddress').value.trim()||null, notes: document.getElementById('prContactNotes').value.trim()||null, created_by: currentUser.id }; if (!payload.name) { showToast('warning',t('fillRequired'),''); return; } const editId = document.getElementById('prContactId').value; let error; if (editId) { ({ error } = await supabaseClient.from('pr_contacts').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_contacts').insert(payload)); } if (error) { showToast('error','Error',error.message); return; } closeModal('prContactModal'); showToast('success','تم الحفظ',payload.name); await loadPRModule(); }
        function editPRContact(id) { const r = prData.contacts.find(x => x.id === id); if (!r) return; openPRModal('prContactModal'); document.getElementById('prContactId').value = r.id; document.getElementById('prContactName').value = r.name || ''; document.getElementById('prContactOrg').value = r.organization || ''; document.getElementById('prContactType').value = r.type || 'client'; document.getElementById('prContactPhone').value = r.phone || ''; document.getElementById('prContactEmail').value = r.email || ''; document.getElementById('prContactAddress').value = r.address || ''; document.getElementById('prContactNotes').value = r.notes || ''; }
        function editPRComm(id) { const r = prData.communications.find(x => x.id === id); if (!r) return; openPRModal('prCommModal'); document.getElementById('prCommId').value = r.id; document.getElementById('prCommContact').value = r.contact_name || ''; document.getElementById('prCommType').value = r.type || ''; document.getElementById('prCommDir').value = r.direction || ''; document.getElementById('prCommSubject').value = r.subject || ''; document.getElementById('prCommSummary').value = r.summary || ''; document.getElementById('prCommDate').value = r.date || ''; }
        function editPRMeeting(id) { const r = prData.meetings.find(x => x.id === id); if (!r) return; openPRModal('prMeetingModal'); document.getElementById('prMeetId').value = r.id; document.getElementById('prMeetTitle').value = r.title || ''; document.getElementById('prMeetDate').value = r.date || ''; document.getElementById('prMeetTime').value = r.time || ''; document.getElementById('prMeetLocation').value = r.location || ''; document.getElementById('prMeetAttendees').value = r.attendees || ''; document.getElementById('prMeetAgenda').value = r.agenda || ''; document.getElementById('prMeetMinutes').value = r.minutes || ''; document.getElementById('prMeetActions').value = r.action_items || ''; }
        function editPRTask(id) { const r = prData.tasks.find(x => x.id === id); if (!r) return; openPRModal('prTaskModal'); document.getElementById('prTaskId').value = r.id; document.getElementById('prTaskTitle').value = r.title || ''; document.getElementById('prTaskDesc').value = r.description || ''; document.getElementById('prTaskPriority').value = r.priority || ''; document.getElementById('prTaskStatus').value = r.status || ''; document.getElementById('prTaskDue').value = r.due_date || ''; document.getElementById('prTaskAssigned').value = r.assigned_to || ''; }
        async function savePRComm() { const payload = { contact_name: document.getElementById('prCommContact').value.trim(), type: document.getElementById('prCommType').value, direction: document.getElementById('prCommDir').value, subject: document.getElementById('prCommSubject').value.trim(), summary: document.getElementById('prCommSummary').value.trim()||null, date: document.getElementById('prCommDate').value || null, created_by: currentUser.id }; if (!payload.contact_name || !payload.subject || !payload.date) { showToast('warning',t('fillRequired'),''); return; } const editId = document.getElementById('prCommId').value; let error; if (editId) { ({ error } = await supabaseClient.from('pr_communications').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_communications').insert(payload)); } if (error) { showToast('error','Error',error.message); return; } closeModal('prCommModal'); showToast('success','تم الحفظ',payload.subject); await loadPRModule(); }
        async function savePRMeeting() { const payload = { title: document.getElementById('prMeetTitle').value.trim(), date: document.getElementById('prMeetDate').value || null, time: document.getElementById('prMeetTime').value||null, location: document.getElementById('prMeetLocation').value.trim()||null, attendees: document.getElementById('prMeetAttendees').value.trim()||null, agenda: document.getElementById('prMeetAgenda').value.trim()||null, minutes: document.getElementById('prMeetMinutes').value.trim()||null, action_items: document.getElementById('prMeetActions').value.trim()||null, created_by: currentUser.id }; if (!payload.title || !payload.date) { showToast('warning',t('fillRequired'),''); return; } const editId = document.getElementById('prMeetId').value; let error; if (editId) { ({ error } = await supabaseClient.from('pr_meetings').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_meetings').insert(payload)); } if (error) { showToast('error','Error',error.message); return; } closeModal('prMeetingModal'); showToast('success','تم الحفظ',payload.title); await loadPRModule(); }
        async function savePRTask() { const payload = { title: document.getElementById('prTaskTitle').value.trim(), description: document.getElementById('prTaskDesc').value.trim()||null, priority: document.getElementById('prTaskPriority').value, status: document.getElementById('prTaskStatus').value, due_date: document.getElementById('prTaskDue').value||null, assigned_to: document.getElementById('prTaskAssigned').value.trim()||null, created_by: currentUser.id }; if (!payload.title) { showToast('warning',t('fillRequired'),''); return; } const editId = document.getElementById('prTaskId').value; let error; if (editId) { ({ error } = await supabaseClient.from('pr_tasks').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_tasks').insert(payload)); } if (error) { showToast('error','Error',error.message); return; } closeModal('prTaskModal'); showToast('success','تم الحفظ',payload.title); await loadPRModule(); }
        async function savePRInvoice() { const btn = document.getElementById('prInvSaveBtn'); btn.disabled = true; let imagePath = null; const editId = document.getElementById('prInvId').value; const file = document.getElementById('prInvImage').files[0]; if (file) { try { document.getElementById('prInvUploadStatus').textContent = 'جاري رفع الصورة...'; imagePath = await uploadPRImage(file, 'invoices'); document.getElementById('prInvUploadStatus').textContent = '✅ تم الرفع'; } catch(e) { showToast('error','فشل رفع الصورة',e.message); btn.disabled = false; return; } } if (!file && editId) { const ex = prData.invoices.find(x => x.id === editId); imagePath = ex ? (ex.image_path || null) : null; } const payload = { number: document.getElementById('prInvNumber').value.trim(), client: document.getElementById('prInvClient').value.trim(), amount: parseFloat(document.getElementById('prInvAmount').value)||0, currency: data.settings.currency||'SDG', status: document.getElementById('prInvStatus').value, date: document.getElementById('prInvDate').value || null, due_date: document.getElementById('prInvDue').value||null, description: document.getElementById('prInvDesc').value.trim()||null, image_path: imagePath, created_by: currentUser.id }; if (!payload.number || !payload.client || !payload.date) { showToast('warning',t('fillRequired'),''); btn.disabled=false; return; } let error; if (editId) { ({ error } = await supabaseClient.from('pr_invoices').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_invoices').insert(payload)); } btn.disabled = false; if (error) { showToast('error','Error',error.message); return; } closeModal('prInvoiceModal'); showToast('success','تم حفظ الفاتورة',payload.number); await loadPRModule(); }
        function editPRInvoice(id) { const r = prData.invoices.find(x => x.id === id); if (!r) return; openPRModal('prInvoiceModal'); document.getElementById('prInvId').value = r.id; document.getElementById('prInvNumber').value = r.number || ''; document.getElementById('prInvClient').value = r.client || ''; document.getElementById('prInvAmount').value = (r.amount != null ? r.amount : ''); document.getElementById('prInvStatus').value = r.status || ''; document.getElementById('prInvDate').value = r.date || ''; document.getElementById('prInvDue').value = r.due_date || ''; document.getElementById('prInvDesc').value = r.description || ''; document.getElementById('prInvImage').value = ''; const us = document.getElementById('prInvUploadStatus'); if (us) us.textContent = r.image_path ? 'صورة مرفقة — اتركها فارغة للإبقاء عليها' : ''; }
        function editPRBank(id) { const r = prData.bank.find(x => x.id === id); if (!r) return; openPRModal('prBankModal'); document.getElementById('prBankId').value = r.id; document.getElementById('prBankName').value = r.bank_name || ''; document.getElementById('prBankType').value = r.notification_type || ''; document.getElementById('prBankAmount').value = (r.amount != null ? r.amount : ''); document.getElementById('prBankRef').value = r.reference || ''; document.getElementById('prBankDate').value = r.date || ''; document.getElementById('prBankDesc').value = r.description || ''; document.getElementById('prBankImage').value = ''; const us = document.getElementById('prBankUploadStatus'); if (us) us.textContent = r.image_path ? 'صورة مرفقة — اتركها فارغة للإبقاء عليها' : ''; }
        async function savePRBank() { const btn = document.getElementById('prBankSaveBtn'); btn.disabled = true; let imagePath = null; const editId = document.getElementById('prBankId').value; const file = document.getElementById('prBankImage').files[0]; if (file) { try { document.getElementById('prBankUploadStatus').textContent = 'جاري رفع الصورة...'; imagePath = await uploadPRImage(file, 'bank'); document.getElementById('prBankUploadStatus').textContent = '✅ تم الرفع'; } catch(e) { showToast('error','فشل رفع الصورة',e.message); btn.disabled=false; return; } } if (!file && editId) { const ex = prData.bank.find(x => x.id === editId); imagePath = ex ? (ex.image_path || null) : null; } const payload = { bank_name: document.getElementById('prBankName').value.trim(), notification_type: document.getElementById('prBankType').value, amount: parseFloat(document.getElementById('prBankAmount').value)||null, currency: data.settings.currency||'SDG', reference: document.getElementById('prBankRef').value.trim()||null, date: document.getElementById('prBankDate').value || null, description: document.getElementById('prBankDesc').value.trim()||null, image_path: imagePath, created_by: currentUser.id }; if (!payload.bank_name || !payload.date) { showToast('warning',t('fillRequired'),''); btn.disabled=false; return; } let error; if (editId) { ({ error } = await supabaseClient.from('pr_bank_notifications').update(payload).eq('id', editId)); } else { ({ error } = await supabaseClient.from('pr_bank_notifications').insert(payload)); } btn.disabled = false; if (error) { showToast('error','Error',error.message); return; } closeModal('prBankModal'); showToast('success','تم حفظ الإشعار',payload.bank_name); await loadPRModule(); }
        async function printPRInvoice(id) {
            const inv = prData.invoices.find(x => String(x.id) === String(id));
            if (!inv) return;
            const company = 'شركة الوطنية للطاقة والهندسة المحدودة';
            const now = new Date().toLocaleDateString('ar-SA');
            const logo = AEECO_INVOICE_LOGO;
            const statAr = {pending:'انتظار',paid:'مدفوعة',overdue:'متأخرة',cancelled:'ملغاة'};
            const imgHtml = await _prSignedImg(inv.image_path);
            const amount = (parseFloat(inv.amount) || 0).toLocaleString();
            const rows = `<tr><th>رقم الفاتورة</th><td>${esc(inv.number)}</td></tr><tr><th>العميل</th><td>${esc(inv.client)}</td></tr><tr><th>المبلغ</th><td>${amount} ${esc(inv.currency)}</td></tr><tr><th>الحالة</th><td>${statAr[inv.status] || esc(inv.status)}</td></tr><tr><th>التاريخ</th><td>${esc(inv.date)}</td></tr><tr><th>تاريخ الاستحقاق</th><td>${esc(inv.due_date || '-')}</td></tr><tr><th>الوصف</th><td>${esc(inv.description || '-')}</td></tr>`;
            const win = window.open('', '_blank');
            win.document.write(`<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8"><title>فاتورة ${esc(inv.number)}</title><style>${_prPrintCSS()}</style></head><body><div class="head">${logo ? `<img src="${logo}">` : ''}<div class="doc">فاتورة</div></div><table>${rows}</table>${imgHtml}<div class="footer">طُبع من نظام ${esc(company)} — ${now}</div><br><button onclick="window.print()" style="padding:10px 20px;font-size:14px;cursor:pointer">🖨️ طباعة / حفظ PDF</button></body></html>`);
            win.document.close();
        }
        async function printPRBank(id) {
            const b = prData.bank.find(x => String(x.id) === String(id));
            if (!b) return;
            const company = 'شركة الوطنية للطاقة والهندسة المحدودة';
            const now = new Date().toLocaleDateString('ar-SA');
            const logo = AEECO_INVOICE_LOGO;
            const typeAr = {credit:'إيداع',debit:'سحب',transfer:'تحويل',other:'أخرى'};
            const imgHtml = await _prSignedImg(b.image_path);
            const amount = b.amount ? (parseFloat(b.amount) || 0).toLocaleString() + ' ' + esc(b.currency) : '-';
            const rows = `<tr><th>التاريخ</th><td>${esc(b.date)}</td></tr><tr><th>اسم البنك</th><td>${esc(b.bank_name)}</td></tr><tr><th>النوع</th><td>${typeAr[b.notification_type] || esc(b.notification_type)}</td></tr><tr><th>المبلغ</th><td>${amount}</td></tr><tr><th>المرجع</th><td>${esc(b.reference || '-')}</td></tr><tr><th>الوصف</th><td>${esc(b.description || '-')}</td></tr>`;
            const win = window.open('', '_blank');
            win.document.write(`<!DOCTYPE html><html dir="rtl"><head><meta charset="UTF-8"><title>إشعار بنكي</title><style>${_prPrintCSS()}</style></head><body><div class="head">${logo ? `<img src="${logo}">` : ''}<div class="doc">إشعار بنكي</div></div><table>${rows}</table>${imgHtml}<div class="footer">طُبع من نظام ${esc(company)} — ${now}</div><br><button onclick="window.print()" style="padding:10px 20px;font-size:14px;cursor:pointer">🖨️ طباعة / حفظ PDF</button></body></html>`);
            win.document.close();
        }
        async function checkMeetingReminder() {
            if (!currentUser || !['pr','gm','admin'].includes(currentUser.role)) return;
            try { if (sessionStorage.getItem('aeeco_meeting_dismissed') === '1') return; } catch (e) {}
            var el = document.getElementById('meetingReminder');
            var txt = document.getElementById('meetingReminderText');
            if (!el) return;
            try {
                var today = new Date(); today.setHours(0,0,0,0);
                var todayStr = today.toISOString().slice(0,10);
                var soonDate = new Date(today.getTime() + 2*86400000);
                var soonStr = soonDate.toISOString().slice(0,10);
                const { data: meets } = await supabaseClient.from('pr_meetings').select('title,date,time').gte('date', todayStr).lte('date', soonStr).order('date', { ascending: true });
                if (!meets || meets.length === 0) { el.classList.add('app-hidden'); return; }
                var mt = meets[0];
                var label;
                if (mt.date === todayStr) {
                    label = 'عندك اجتماع النهاردة: ' + mt.title + (mt.time ? ' الساعة ' + mt.time : '');
                } else {
                    var dt = new Date(mt.date + 'T00:00:00');
                    var isTomorrow = Math.round((dt - today) / 86400000) === 1;
                    label = (isTomorrow ? 'عندك اجتماع بكرة: ' : ('عندك اجتماع يوم ' + formatDate(mt.date) + ': ')) + mt.title;
                }
                if (meets.length > 1) label += ' (و' + (meets.length - 1) + ' اجتماع آخر قريب)';
                if (txt) txt.textContent = label;
                el.classList.remove('app-hidden');
            } catch(e) { console.error('checkMeetingReminder', e); }
        }
        function renderProducts() { const tbody = document.getElementById('productsTableBody'); if (data.products.length === 0) { tbody.innerHTML = `<tr><td colspan="6" style="text-align: center; padding: 40px;">${t('noData')}</td></tr>`; return; } tbody.innerHTML = data.products.map(prod => `<tr><td style="font-family: var(--font-mono);">${esc(prod.sku)}</td><td>${esc(prod.name)}</td><td>${esc(prod.category || '-')}</td><td>${prod.stock}</td><td style="font-family: var(--font-mono);">${formatCurrency(prod.sellingPrice)}</td><td><button class="btn btn-sm btn-secondary" onclick="viewProduct('${prod.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="editProduct('${prod.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteProduct('${prod.id}')"><i class="fas fa-trash"></i></button></td></tr>`).join(''); }
        function viewPRTask(id){ var r=(prData.tasks||[]).find(function(x){return x.id===id;}); if(!r) return; showDetailsModal('تفاصيل المهمة', [['العنوان',esc(r.title||'-')],['الوصف',esc(r.description||'-')],['الأولوية',esc(r.priority||'-')],['الحالة',esc(r.status||'-')],['تاريخ الاستحقاق',r.due_date?formatDate(r.due_date):'-'],['مسند إلى',esc(r.assigned_to||'-')]]); }
        function viewPRContact(id){ var r=(prData.contacts||[]).find(function(x){return x.id===id;}); if(!r) return; showDetailsModal('تفاصيل جهة الاتصال', [['الاسم',esc(r.name||'-')],['الجهة',esc(r.organization||'-')],['النوع',esc(r.type||'-')],['الهاتف',esc(r.phone||'-')],['البريد',esc(r.email||'-')],['العنوان',esc(r.address||'-')],['ملاحظات',esc(r.notes||'-')]]); }
        function viewPRMeeting(id){ var r=(prData.meetings||[]).find(function(x){return x.id===id;}); if(!r) return; showDetailsModal('تفاصيل الاجتماع', [['العنوان',esc(r.title||'-')],['التاريخ',r.date?formatDate(r.date):'-'],['الوقت',esc(r.time||'-')],['المكان',esc(r.location||'-')],['الحضور',esc(r.attendees||'-')],['جدول الأعمال',esc(r.agenda||'-')],['المحضر',esc(r.minutes||'-')],['الإجراءات',esc(r.action_items||'-')]]); }
        function viewPRInvoice(id){ var r=(prData.invoices||[]).find(function(x){return x.id===id;}); if(!r) return; showDetailsModal('تفاصيل الفاتورة', [['رقم الفاتورة',esc(r.number||'-')],['العميل',esc(r.client||'-')],['المبلغ',r.amount!=null?formatCurrency(r.amount):'-'],['الحالة',esc(r.status||'-')],['التاريخ',r.date?formatDate(r.date):'-'],['تاريخ الاستحقاق',r.due_date?formatDate(r.due_date):'-'],['الوصف',esc(r.description||'-')]]); }
        function viewProduct(id){ var r=(data.products||[]).find(function(x){return x.id===id;}); if(!r) return; showDetailsModal('تفاصيل المنتج', [['SKU',esc(r.sku||'-')],['الاسم',esc(r.name||'-')],['الفئة',esc(r.category||'-')],['المخزون',(r.stock!=null?r.stock:'-')],['سعر التكلفة',r.costPrice!=null?formatCurrency(r.costPrice):'-'],['سعر البيع',r.sellingPrice!=null?formatCurrency(r.sellingPrice):'-'],['المورّد',esc(r.supplier||'-')]]); }
