        async function loadTickets() { try { const { data: rows, error } = await supabaseClient.from('tickets').select('*').order('createdAt', { ascending: false }); if (error) console.warn('tickets:', error.message); else data.tickets = rows || []; } catch (e) { console.warn('tickets:', e); } renderTickets(); }
        async function loadEquipment() { try { const { data: rows, error } = await supabaseClient.from('equipment').select('*').order('createdAt', { ascending: false }); if (error) console.warn('equipment:', error.message); else data.equipment = rows || []; } catch (e) { console.warn('equipment:', e); } renderEquipment(); }

        document.querySelectorAll('.tab[data-reqtab]').forEach(tab => { tab.addEventListener('click', function(e) { e.stopImmediatePropagation(); document.querySelectorAll('.tab[data-reqtab]').forEach(t => t.classList.remove('active')); this.classList.add('active'); activeReqTab = this.dataset.reqtab; const isIt = activeReqTab === 'itticket'; const isMy = activeReqTab === 'myit'; document.getElementById('requestsMainTable').style.display = (isIt||isMy) ? 'none' : 'table'; document.getElementById('itTicketForm').style.display = isIt ? 'block' : 'none'; var _myv = document.getElementById('myITTicketsView'); if(_myv) _myv.style.display = isMy ? 'block' : 'none'; if (isMy) renderMyITTickets(); else if (!isIt) renderRequestsTable(); }); });
        function renderMyITTickets(){
          var box = document.getElementById('itMyTicketsList'); if(!box) return;
          var mine = (data.tickets||[]).filter(function(tk){ return tk.created_by === currentUser.id; });
          if(mine.length === 0){ box.innerHTML = '<div style="color:var(--text-muted);font-size:13px;padding:12px 0;">لا توجد تذاكر بعد.</div>'; return; }
          var statusMap = {open:['badge-danger','مفتوحة'], in_progress:['badge-warning','قيد المعالجة'], resolved:['badge-success','تم الحل'], closed:['badge-gray','مغلقة']};
          box.innerHTML = mine.map(function(tk){
            var sb = statusMap[tk.status] || ['badge-gray', tk.status];
            var canEdit = (tk.status === 'open');
            return `<div style="background:var(--bg-tertiary);border:1px solid var(--border-color);border-radius:10px;padding:12px 14px;margin-bottom:10px;display:flex;align-items:center;justify-content:space-between;gap:10px;"><div style="flex:1;min-width:0;"><div style="font-weight:600;font-size:14px;">${esc(tk.title)}</div><div style="font-size:12px;color:var(--text-muted);margin-top:3px;"><span class="badge ${sb[0]}">${sb[1]}</span> · ${formatDateTime(tk.createdAt)}</div></div>${canEdit ? `<button class="btn btn-sm btn-secondary" onclick="editMyITTicket('${tk.id}')" title="تعديل"><i class="fas fa-edit"></i></button>` : `<span style="font-size:11px;color:var(--text-muted);" title="بدأ الدعم الفني معالجتها"><i class="fas fa-lock"></i></span>`}</div>`;
          }).join('');
        }
        function editMyITTicket(id){
          var tk = (data.tickets||[]).find(function(x){ return String(x.id) === String(id); });
          if(!tk) return;
          if(tk.created_by !== currentUser.id){ showToast('error','غير مسموح','يمكنك تعديل تذاكرك فقط'); return; }
          if(tk.status !== 'open'){ showToast('warning','لا يمكن التعديل','بدأ الدعم الفني معالجة التذكرة'); return; }
          _editITId = id; activeReqTab='itticket'; document.querySelectorAll('.tab[data-reqtab]').forEach(function(_t){ _t.classList.toggle('active', _t.dataset.reqtab==='itticket'); }); var _rm0=document.getElementById('requestsMainTable'); if(_rm0) _rm0.style.display='none'; var _mv0=document.getElementById('myITTicketsView'); if(_mv0) _mv0.style.display='none'; var _tf0=document.getElementById('itTicketForm'); if(_tf0) _tf0.style.display='block';
          document.getElementById('itTitle').value = tk.title || '';
          document.getElementById('itDesc').value = tk.description || '';
          if(document.getElementById('itPriority')) document.getElementById('itPriority').value = tk.priority || 'medium';
          if(document.getElementById('itCategory') && tk.category) document.getElementById('itCategory').value = tk.category;
          var sb = document.getElementById('itSubmitBtn'); if(sb) sb.innerHTML = '<i class="fas fa-save"></i> حفظ التعديل';
          var cb = document.getElementById('itCancelEditBtn'); if(cb) cb.style.display = '';
          var form = document.getElementById('itTicketForm'); if(form) form.scrollIntoView({behavior:'smooth', block:'start'});
        }
        function cancelEditITTicket(){
          _editITId = null;
          document.getElementById('itTitle').value = '';
          document.getElementById('itDesc').value = '';
          var sb = document.getElementById('itSubmitBtn'); if(sb) sb.innerHTML = '<i class="fas fa-paper-plane"></i> <span data-i18n="submitRequest">إرسال الطلب</span>';
          var cb = document.getElementById('itCancelEditBtn'); if(cb) cb.style.display = 'none'; activeReqTab='myit'; document.querySelectorAll('.tab[data-reqtab]').forEach(function(_t){ _t.classList.toggle('active', _t.dataset.reqtab==='myit'); }); var _rm1=document.getElementById('requestsMainTable'); if(_rm1) _rm1.style.display='none'; var _tf1=document.getElementById('itTicketForm'); if(_tf1) _tf1.style.display='none'; var _mv1=document.getElementById('myITTicketsView'); if(_mv1) _mv1.style.display='block'; renderMyITTickets();
        }
        async function submitITTicketFromRequests() { const title = document.getElementById('itTitle').value.trim(); const desc = document.getElementById('itDesc').value.trim(); if (!title || !desc) { showToast('warning', t('fillRequired'), ''); return; } const _itPr = document.getElementById('itPriority').value; const _itCat = document.getElementById('itCategory').value; if (_editITId) { const { data: _ud, error: _ue } = await supabaseClient.from('tickets').update({ title, description: desc, priority: _itPr, category: _itCat }).eq('id', _editITId).eq('created_by', currentUser.id).eq('status', 'open').select(); if (_ue) { showToast('error', 'خطأ', _ue.message); return; } if (!_ud || _ud.length === 0) { showToast('error', 'تعذّر الحفظ', 'لم يتم تحديث التذكرة. تأكّد من تشغيل ملف 34_ticket_owner_access.sql على Supabase'); return; } logActivity('IT Support', 'update', title); cancelEditITTicket(); await loadTickets(); renderMyITTickets(); showToast('success', 'تم تعديل التذكرة', title); return; } const ticket = { id: generateId(), created_by: currentUser.id, title, description: desc, priority: _itPr, category: _itCat, status: 'open', createdAt: new Date().toISOString(), submittedBy: currentUser.full_name }; const { error } = await supabaseClient.from('tickets').insert(ticket); if (error) { showToast('error', 'Error', error.message); return; } logActivity('IT Support', 'create', title); document.getElementById('itTitle').value = ''; document.getElementById('itDesc').value = ''; await loadTickets(); renderMyITTickets(); showToast('success', t('requestSubmitted'), title); }
        async function uploadTicketImage(file, folder){
            const ext = file.name.split('.').pop();
            const path = `${folder}/${Date.now()}.${ext}`;
            const { data, error } = await supabaseClient.storage.from('ticket-images').upload(path, file);
            if(error) throw error;
            return data.path;
        }
        async function uploadEquipmentImage(file, folder){
            const ext = file.name.split('.').pop();
            const path = `${folder}/${Date.now()}.${ext}`;
            const { data, error } = await supabaseClient.storage.from('equipment-images').upload(path, file);
            if(error) throw error;
            return data.path;
        }
        async function confirmResolveTicket(){
            const id = document.getElementById('resolveTicketId').value;
            const note = document.getElementById('resolveNote').value.trim();
            const tk = data.tickets.find(x=>String(x.id)===String(id));
            if(!tk) return;
            const _wasResolved = tk.status === 'resolved';
            const updated = Object.assign({}, tk, { status: 'resolved', resolution_note: note || null });
            const { error } = await supabaseClient.from('tickets').upsert(updated);
            if(error){ showToast('error','خطأ', error.message); return; }
            logActivity('IT Support','resolve', tk.title);
            closeModal('resolveTicketModal');
            if(!_wasResolved && tk.created_by){
                const msg = note ? ('تم حل المشكلة. ملاحظة الدعم الفني: ' + note) : 'تم حل المشكلة، يمكنك استلام جهازك من الدعم الفني.';
                await notifyUser(tk.created_by, '✅ تم حل تذكرتك: '+tk.title, msg, 'success', 'support');
            }
            await loadTickets();
            showToast('success','تم حل التذكرة', tk.title);
        }
        async function saveTicket() { const id = document.getElementById('ticketId').value || generateId(); const isNew = !document.getElementById('ticketId').value; const _existing = isNew ? null : data.tickets.find(t => t.id === id); const ticket = {id: id, created_by: isNew ? currentUser.id : (_existing ? _existing.created_by : null), submittedBy: isNew ? currentUser.full_name : (_existing ? _existing.submittedBy : null), title: document.getElementById('ticketTitle').value, description: document.getElementById('ticketDescription').value, priority: document.getElementById('ticketPriority').value, category: document.getElementById('ticketCategory').value, status: (isNew && !['gm','admin'].includes(currentUser.role)) ? 'open' : document.getElementById('ticketStatus').value, createdAt: isNew ? new Date().toISOString() : (data.tickets.find(t => t.id === id)?.createdAt || new Date().toISOString())}; if(!isNew && _existing){ ticket.title = _existing.title; ticket.description = _existing.description; } const _tkFile = document.getElementById('ticketImage'); let _tkImg = isNew ? null : (_existing ? _existing.image_path : null); var _canImg=isNew; if(_tkFile && _tkFile.files && _tkFile.files[0] && _canImg){ const _ts = document.getElementById('ticketUploadStatus'); if(_ts) _ts.textContent='جارٍ رفع الصورة...'; try { _tkImg = await uploadTicketImage(_tkFile.files[0], 'tickets'); } catch(err){ showToast('error','تعذّر رفع الصورة', err.message||''); if(_ts) _ts.textContent=''; return; } if(_ts) _ts.textContent=''; } ticket.image_path = _tkImg; ticket.resolution_note = (isNew ? null : (_existing && _existing.resolution_note ? _existing.resolution_note : null)); const { error } = await supabaseClient.from('tickets').upsert(ticket); if (error) { showToast('error', 'Error', error.message); return; } logActivity('IT Support', isNew ? 'create' : 'update', ticket.title); if (!isNew && ticket.status === 'resolved' && _existing && _existing.status !== 'resolved' && ticket.created_by) { await notifyUser(ticket.created_by, '✅ تم حل تذكرتك: ' + ticket.title, 'تم حل المشكلة، يمكنك استلام جهازك من الدعم الفني.', 'success', 'support'); } await loadTickets(); closeModal('ticketModal'); showToast('success', t('dataSaved'), ticket.title); }
        function renderTickets() { const openCount = data.tickets.filter(t => t.status === 'open' || t.status === 'in_progress').length; const _oc = document.getElementById('openTicketsCount'); if (_oc) { _oc.textContent = openCount; _oc.classList.toggle('app-hidden', openCount === 0); } const _soc = document.getElementById('statOpenTickets'); if (_soc) _soc.textContent = openCount; const tbody = document.getElementById('ticketsTableBody'); if (data.tickets.length === 0) { tbody.innerHTML = `<tr><td colspan="6" style="text-align: center; padding: 40px;">${t('noData')}</td></tr>`; return; } tbody.innerHTML = data.tickets.map(ticket => { const priorityBadge = {low: 'badge-gray', medium: 'badge-info', high: 'badge-warning', critical: 'badge-danger'}[ticket.priority]; const statusBadge = {open: 'badge-danger', in_progress: 'badge-warning', resolved: 'badge-success', closed: 'badge-gray'}[ticket.status]; return `<tr><td style="font-family: var(--font-mono);">#${ticket.id.slice(-6).toUpperCase()}</td><td>${esc(ticket.title)}</td><td><span class="badge ${statusBadge}">${t(ticket.status)}</span></td><td><span class="badge ${priorityBadge}">${t(ticket.priority)}</span></td><td>${formatDateTime(ticket.createdAt)}</td><td><button class="btn btn-sm btn-secondary" onclick="viewTicket('${ticket.id}')"><i class="fas fa-eye"></i></button> ${['gm','admin','it_support'].includes(currentUser.role) ? ((ticket.status==='open'||ticket.status==='in_progress') ? `<button class="btn btn-sm btn-success" onclick="resolveTicket('${ticket.id}')" title="تم الحل"><i class="fas fa-check"></i></button> ` : '') + `<button class="btn btn-sm btn-secondary" onclick="editTicket('${ticket.id}')"><i class="fas fa-edit"></i></button> ` + (['gm','admin'].includes(currentUser.role) ? `<button class="btn btn-sm btn-danger" onclick="deleteTicket('${ticket.id}')"><i class="fas fa-trash"></i></button>` : '') : ''}</td></tr>`; }).join(''); }
        function editTicket(id) { const ticket = data.tickets.find(t => t.id === id); if (ticket) { document.getElementById('ticketId').value = ticket.id; document.getElementById('ticketTitle').value = ticket.title; document.getElementById('ticketDescription').value = ticket.description; document.getElementById('ticketPriority').value = ticket.priority; document.getElementById('ticketCategory').value = ticket.category; document.getElementById('ticketStatus').value = ticket.status; const _ti=document.getElementById('ticketImage'); if(_ti) _ti.value=''; const _ts=document.getElementById('ticketUploadStatus'); if(_ts) _ts.textContent = ticket.image_path ? 'يوجد صورة مرفقة (ارفع جديدة لاستبدالها)' : ''; var _isOwner=false; /* المحتوى مقفول دائماً عند تعديل تذكرة موجودة — تعديل الحالة/الأولوية/الفئة فقط */ var _tt=document.getElementById('ticketTitle'), _td=document.getElementById('ticketDescription'); if(_tt){ _tt.readOnly=!_isOwner; _tt.classList.toggle('field-locked', !_isOwner); } if(_td){ _td.readOnly=!_isOwner; _td.classList.toggle('field-locked', !_isOwner); } var _h=document.getElementById('ticketLockHint'); if(!_isOwner){ if(!_h && _td){ _h=document.createElement('div'); _h.id='ticketLockHint'; _h.style.cssText='font-size:12px;color:var(--warning);margin-top:8px'; _h.innerHTML='<i class="fas fa-lock"></i> بيانات الطلب (العنوان والوصف والصورة) من إنشاء مقدّمه ولا يمكن تعديلها. يمكنك تغيير الحالة والأولوية والفئة فقط.'; _td.parentNode.appendChild(_h); } else if(_h){ _h.style.display='block'; } } else if(_h){ _h.style.display='none'; } var _img=document.getElementById('ticketImage'); if(_img){ var _ig=_img.closest('.form-group'); if(_ig) _ig.style.display=_isOwner?'':'none'; } openModal('ticketModal'); } }
        async function deleteTicket(id) { if (!(await confirmStyled(t('confirmDelete'), {type:'danger'}))) return; const ticket = data.tickets.find(t => t.id === id); const { error } = await supabaseClient.from('tickets').delete().eq('id', id); if (error) { showToast('error', 'Error', error.message); return; } logActivity('IT Support', 'delete', ticket?.title || id); await loadTickets(); showToast('success', t('dataDeleted'), ''); }
        async function saveEquipment() { const id = document.getElementById('equipmentId').value || generateId(); const isNew = !document.getElementById('equipmentId').value; const equipment = {id: id, assetId: document.getElementById('equipmentAssetId').value, name: document.getElementById('equipmentName').value, category: document.getElementById('equipmentCategory').value, status: document.getElementById('equipmentStatus').value, assignedTo: document.getElementById('equipmentAssignedTo').value, location: document.getElementById('equipmentLocation').value, notes: document.getElementById('equipmentNotes').value, createdAt: isNew ? new Date().toISOString() : (data.equipment.find(e => e.id === id)?.createdAt || new Date().toISOString())}; const _eqFile = document.getElementById('equipmentImage'); let _eqImg = isNew ? null : (data.equipment.find(e => e.id === id)?.image_path || null); if(_eqFile && _eqFile.files && _eqFile.files[0]){ const _st = document.getElementById('equipmentUploadStatus'); if(_st) _st.textContent = 'جارٍ رفع الصورة...'; try { _eqImg = await uploadEquipmentImage(_eqFile.files[0], 'equipment'); } catch(err){ showToast('error','تعذّر رفع الصورة', err.message||''); if(_st) _st.textContent=''; return; } if(_st) _st.textContent=''; } equipment.image_path = _eqImg; const { error } = await supabaseClient.from('equipment').upsert(equipment); if (error) { showToast('error', 'Error', error.message); return; } logActivity('Equipment', isNew ? 'create' : 'update', equipment.name); await loadEquipment(); closeModal('equipmentModal'); showToast('success', t('dataSaved'), equipment.name); }
        function renderEquipment() { const tbody = document.getElementById('equipmentTableBody'); if (data.equipment.length === 0) { tbody.innerHTML = `<tr><td colspan="7" style="text-align: center; padding: 40px;">${t('noData')}</td></tr>`; return; } tbody.innerHTML = data.equipment.map(item => { const statusBadge = {available: 'badge-success', in_use: 'badge-info', maintenance: 'badge-warning', retired: 'badge-gray'}[item.status]; return `<tr><td style="font-family: var(--font-mono);">${esc(item.assetId)}</td><td>${esc(item.name)}</td><td>${t(item.category)}</td><td>${esc(item.assignedTo || '-')}</td><td>${esc(item.location || '-')}</td><td><span class="badge ${statusBadge}">${t(item.status)}</span></td><td><button class="btn btn-sm btn-secondary" onclick="viewEquipment('${item.id}')" title="عرض"><i class="fas fa-eye"></i></button> <button class="btn btn-sm btn-secondary" onclick="editEquipment('${item.id}')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-danger" onclick="deleteEquipment('${item.id}')"><i class="fas fa-trash"></i></button></td></tr>`; }).join(''); }
        function editEquipment(id) { const item = data.equipment.find(e => e.id === id); if (item) { document.getElementById('equipmentId').value = item.id; document.getElementById('equipmentAssetId').value = item.assetId; document.getElementById('equipmentName').value = item.name; document.getElementById('equipmentCategory').value = item.category; document.getElementById('equipmentStatus').value = item.status; document.getElementById('equipmentAssignedTo').value = item.assignedTo; document.getElementById('equipmentLocation').value = item.location || ''; document.getElementById('equipmentNotes').value = item.notes; const _ei=document.getElementById('equipmentImage'); if(_ei) _ei.value=''; const _es=document.getElementById('equipmentUploadStatus'); if(_es) _es.textContent = item.image_path ? 'يوجد صورة محفوظة (ارفع صورة جديدة لاستبدالها)' : ''; openModal('equipmentModal'); } }
        async function deleteEquipment(id) { if (!(await confirmStyled(t('confirmDelete'), {type:'danger'}))) return; const item = data.equipment.find(e => e.id === id); const { error } = await supabaseClient.from('equipment').delete().eq('id', id); if (error) { showToast('error', 'Error', error.message); return; } logActivity('Equipment', 'delete', item?.name || id); await loadEquipment(); showToast('success', t('dataDeleted'), ''); }
